# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Artru/Bureau/pong/.Xil/Vivado-6396-LAPTOP-ARTRU/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/CLK_DIGIT.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/ClkDivider.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/RGB_controller.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/boutton.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/breakNumber.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/buzzer.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/chrono.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/clk_min.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/clk_sec.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/clock_vga.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/digit.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/digit_screen.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/dot.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/draw_balle.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/draw_border.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/draw_dotline.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/draw_paddle.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/draw_winner.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/driver7Segments.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/frame_c.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/move_ball.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/number_screen.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/paddle_driver.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/ps2_keyboard.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/score.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/vga_controller_640_60.vhd
      E:/Artru/Bureau/pong/Pong_vhdl.srcs/sources_1/new/pong.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pong
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/Artru/Bureau/pong/.Xil/Vivado-6396-LAPTOP-ARTRU/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
